[package]
name = "demo-only-nft-minter-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.demo-only-nft-minter]
path = ".."

[dependencies.multiversx-sc-meta-lib]
version = "0.56.1"
default-features = false
