// Code generated by the multiversx-sc proxy generator. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

#![allow(dead_code)]
#![allow(clippy::all)]

use multiversx_sc::proxy_imports::*;

pub struct NftStakingProxy;

impl<Env, From, To, Gas> TxProxyTrait<Env, From, To, Gas> for NftStakingProxy
where
    Env: TxEnv,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    type TxProxyMethods = NftStakingProxyMethods<Env, From, To, Gas>;

    fn proxy_methods(self, tx: Tx<Env, From, To, (), Gas, (), ()>) -> Self::TxProxyMethods {
        NftStakingProxyMethods { wrapped_tx: tx }
    }
}

pub struct NftStakingProxyMethods<Env, From, To, Gas>
where
    Env: TxEnv,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    wrapped_tx: Tx<Env, From, To, (), Gas, (), ()>,
}

#[rustfmt::skip]
impl<Env, From, Gas> NftStakingProxyMethods<Env, From, (), Gas>
where
    Env: TxEnv,
    Env::Api: VMApi,
    From: TxFrom<Env>,
    Gas: TxGas<Env>,
{
    pub fn init(
        self,
    ) -> TxTypedDeploy<Env, From, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_deploy()
            .original_result()
    }
}

#[rustfmt::skip]
impl<Env, From, To, Gas> NftStakingProxyMethods<Env, From, To, Gas>
where
    Env: TxEnv,
    Env::Api: VMApi,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    pub fn upgrade(
        self,
    ) -> TxTypedUpgrade<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_upgrade()
            .original_result()
    }
}

#[rustfmt::skip]
impl<Env, From, To, Gas> NftStakingProxyMethods<Env, From, To, Gas>
where
    Env: TxEnv,
    Env::Api: VMApi,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    pub fn stake(
        self,
    ) -> TxTypedCall<Env, From, To, (), Gas, BigUint<Env::Api>> {
        self.wrapped_tx
            .raw_call("stake")
            .original_result()
    }

    pub fn unstake<
        Arg0: ProxyArg<MultiValueManagedVec<Env::Api, EsdtTokenPayment<Env::Api>>>,
    >(
        self,
        unstake_request: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, BigUint<Env::Api>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("unstake")
            .argument(&unstake_request)
            .original_result()
    }

    pub fn claim_unstaked(
        self,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("claimUnstaked")
            .original_result()
    }

    pub fn claim_rewards(
        self,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("claimRewards")
            .original_result()
    }

    pub fn allowed_nft_collections(
        self,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, MultiValueEncoded<Env::Api, TokenIdentifier<Env::Api>>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getAllowedNftCollections")
            .original_result()
    }

    pub fn reward_token_ids(
        self,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, MultiValueEncoded<Env::Api, TokenIdentifier<Env::Api>>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getRewardTokenIds")
            .original_result()
    }

    pub fn stake_quantity<
        Arg0: ProxyArg<ManagedAddress<Env::Api>>,
        Arg1: ProxyArg<TokenIdentifier<Env::Api>>,
        Arg2: ProxyArg<u64>,
    >(
        self,
        address: Arg0,
        token_id: Arg1,
        nonce: Arg2,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, BigUint<Env::Api>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getStakeQuantityRaw")
            .argument(&address)
            .argument(&token_id)
            .argument(&nonce)
            .original_result()
    }

    pub fn staked_items<
        Arg0: ProxyArg<ManagedAddress<Env::Api>>,
    >(
        self,
        address: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, MultiValueEncoded<Env::Api, (TokenIdentifier<Env::Api>, u64)>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getStakedItemsRaw")
            .argument(&address)
            .original_result()
    }

    pub fn nft_collection_score<
        Arg0: ProxyArg<TokenIdentifier<Env::Api>>,
    >(
        self,
        token_id: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, BigUint<Env::Api>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getNftCollectionScore")
            .argument(&token_id)
            .original_result()
    }

    pub fn nft_collection_nonce_score<
        Arg0: ProxyArg<TokenIdentifier<Env::Api>>,
        Arg1: ProxyArg<u64>,
    >(
        self,
        token_id: Arg0,
        nonce: Arg1,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, BigUint<Env::Api>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getNftCollectionNonceScore")
            .argument(&token_id)
            .argument(&nonce)
            .original_result()
    }

    pub fn staking_disabled(
        self,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, bool> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getStakingDisabled")
            .original_result()
    }

    pub fn unstaking_items<
        Arg0: ProxyArg<ManagedAddress<Env::Api>>,
    >(
        self,
        address: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, MultiValueEncoded<Env::Api, (u64, ManagedVec<Env::Api, EsdtTokenPayment<Env::Api>>)>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getUnstakingItemsRaw")
            .argument(&address)
            .original_result()
    }

    pub fn unstaking_penalty(
        self,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, u64> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getUnstakingPenalty")
            .original_result()
    }

    pub fn get_pending_rewards_view<
        Arg0: ProxyArg<ManagedAddress<Env::Api>>,
    >(
        self,
        address: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ManagedVec<Env::Api, EsdtTokenPayment<Env::Api>>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getPendingRewards")
            .argument(&address)
            .original_result()
    }

    pub fn get_staked_items_snapshot<
        Arg0: ProxyArg<ManagedAddress<Env::Api>>,
    >(
        self,
        address: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ManagedVec<Env::Api, EsdtTokenPayment<Env::Api>>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getStakedItems")
            .argument(&address)
            .original_result()
    }

    pub fn get_stake_quantity<
        Arg0: ProxyArg<ManagedAddress<Env::Api>>,
        Arg1: ProxyArg<TokenIdentifier<Env::Api>>,
        Arg2: ProxyArg<u64>,
    >(
        self,
        address: Arg0,
        token_id: Arg1,
        nonce: Arg2,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, BigUint<Env::Api>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getStakeQuantity")
            .argument(&address)
            .argument(&token_id)
            .argument(&nonce)
            .original_result()
    }

    pub fn get_user_staking_score<
        Arg0: ProxyArg<ManagedAddress<Env::Api>>,
    >(
        self,
        address: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, BigUint<Env::Api>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getUserStakingScore")
            .argument(&address)
            .original_result()
    }

    pub fn get_aggregated_staking_score(
        self,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, BigUint<Env::Api>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getAggregatedStakingScore")
            .original_result()
    }

    pub fn get_last_distribution_round(
        self,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, u64> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getLastDistributionRound")
            .original_result()
    }

    pub fn get_reward_rate<
        Arg0: ProxyArg<TokenIdentifier<Env::Api>>,
    >(
        self,
        token_id: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, BigUint<Env::Api>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getRewardRate")
            .argument(&token_id)
            .original_result()
    }

    pub fn is_reward_token<
        Arg0: ProxyArg<TokenIdentifier<Env::Api>>,
    >(
        self,
        token_id: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, bool> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("isRewardToken")
            .argument(&token_id)
            .original_result()
    }

    pub fn user_staked_score<
        Arg0: ProxyArg<ManagedAddress<Env::Api>>,
    >(
        self,
        address: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, BigUint<Env::Api>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getUserStakedScore")
            .argument(&address)
            .original_result()
    }

    pub fn aggregated_staked_score(
        self,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, BigUint<Env::Api>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getAggregatedStakedScore")
            .original_result()
    }

    pub fn current_reward_rate<
        Arg0: ProxyArg<TokenIdentifier<Env::Api>>,
    >(
        self,
        reward_token_id: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, BigUint<Env::Api>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getCurrentRewardRate")
            .argument(&reward_token_id)
            .original_result()
    }

    pub fn user_reward_rate<
        Arg0: ProxyArg<ManagedAddress<Env::Api>>,
        Arg1: ProxyArg<TokenIdentifier<Env::Api>>,
    >(
        self,
        user: Arg0,
        reward_token_id: Arg1,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, BigUint<Env::Api>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getUserRewardRate")
            .argument(&user)
            .argument(&reward_token_id)
            .original_result()
    }

    pub fn user_stored_rewards<
        Arg0: ProxyArg<ManagedAddress<Env::Api>>,
        Arg1: ProxyArg<TokenIdentifier<Env::Api>>,
    >(
        self,
        user: Arg0,
        reward_token_id: Arg1,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, BigUint<Env::Api>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getUserStoredRewards")
            .argument(&user)
            .argument(&reward_token_id)
            .original_result()
    }

    pub fn get_amount_per_round<
        Arg0: ProxyArg<u64>,
        Arg1: ProxyArg<u64>,
        Arg2: ProxyArg<BigUint<Env::Api>>,
    >(
        self,
        start_round: Arg0,
        end_round: Arg1,
        total_distribution_amount: Arg2,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, BigUint<Env::Api>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getDistributionAmountPerRound")
            .argument(&start_round)
            .argument(&end_round)
            .argument(&total_distribution_amount)
            .original_result()
    }

    pub fn last_distribution_round(
        self,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, u64> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getLastDistributionRoundRaw")
            .original_result()
    }

    pub fn distribution_plans(
        self,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, MultiValueEncoded<Env::Api, (TokenIdentifier<Env::Api>, u64, u64, BigUint<Env::Api>)>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getDistributionPlanRaw")
            .original_result()
    }

    pub fn disable_staking(
        self,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("disableStaking")
            .original_result()
    }

    pub fn enable_staking(
        self,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("enableStaking")
            .original_result()
    }

    pub fn allow_collections<
        Arg0: ProxyArg<MultiValueManagedVec<Env::Api, TokenIdentifier<Env::Api>>>,
    >(
        self,
        collections: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("allowCollections")
            .argument(&collections)
            .original_result()
    }

    /// I don't recommend using this function as it won't update user's storage. 
    /// Its effect as of now is to stop other users from staking NFTs from the given collections. 
    pub fn disallow_collections<
        Arg0: ProxyArg<MultiValueManagedVec<Env::Api, TokenIdentifier<Env::Api>>>,
    >(
        self,
        collections: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("disallowCollections")
            .argument(&collections)
            .original_result()
    }

    pub fn distribute_rewards(
        self,
    ) -> TxTypedCall<Env, From, To, (), Gas, ()> {
        self.wrapped_tx
            .raw_call("distributeRewards")
            .original_result()
    }

    pub fn set_unstaking_penalty<
        Arg0: ProxyArg<u64>,
    >(
        self,
        penalty: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("setUnstakingPenalty")
            .argument(&penalty)
            .original_result()
    }

    /// Careful with this function. It will set the score for all NFTs in the collection. 
    /// This will *NOT* update the score for already staked NFTs. 
    pub fn set_collection_score<
        Arg0: ProxyArg<TokenIdentifier<Env::Api>>,
        Arg1: ProxyArg<u64>,
    >(
        self,
        collection: Arg0,
        score: Arg1,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("setCollectionScore")
            .argument(&collection)
            .argument(&score)
            .original_result()
    }

    /// Careful with this function. It will set the score for all NFTs in the collection. 
    /// This will *NOT* update the score for already staked NFTs. 
    pub fn set_collection_nonce_score<
        Arg0: ProxyArg<TokenIdentifier<Env::Api>>,
        Arg1: ProxyArg<u64>,
        Arg2: ProxyArg<u64>,
    >(
        self,
        collection: Arg0,
        nonce: Arg1,
        score: Arg2,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("setCollectionNonceScore")
            .argument(&collection)
            .argument(&nonce)
            .argument(&score)
            .original_result()
    }

    pub fn create_distribution_plan<
        Arg0: ProxyArg<u64>,
        Arg1: ProxyArg<u64>,
    >(
        self,
        start_round: Arg0,
        end_round: Arg1,
    ) -> TxTypedCall<Env, From, To, (), Gas, ()> {
        self.wrapped_tx
            .raw_call("createDistributionPlan")
            .argument(&start_round)
            .argument(&end_round)
            .original_result()
    }

    pub fn remove_distribution_plan<
        Arg0: ProxyArg<TokenIdentifier<Env::Api>>,
        Arg1: ProxyArg<u64>,
        Arg2: ProxyArg<u64>,
        Arg3: ProxyArg<BigUint<Env::Api>>,
    >(
        self,
        reward_token_id: Arg0,
        start_round: Arg1,
        end_round: Arg2,
        amount_per_round: Arg3,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("removeDistributionPlan")
            .argument(&reward_token_id)
            .argument(&start_round)
            .argument(&end_round)
            .argument(&amount_per_round)
            .original_result()
    }
}
